# Generated by Django 3.0.4 on 2020-05-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalID',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('bgColor', models.CharField(max_length=30)),
                ('dragBgColor', models.CharField(max_length=30)),
                ('borderColor', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'CalID',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('studentID', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(default='time', max_length=30)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('isAllDay', models.BooleanField(default=False)),
                ('state', models.CharField(default='Busy', max_length=20)),
                ('calendarClass', models.CharField(default='public', max_length=20)),
                ('calendarID', models.ForeignKey(default='전공 필수', on_delete=django.db.models.deletion.PROTECT, to='toast_cal.CalID')),
            ],
            options={
                'db_table': 'Calendar',
            },
        ),
    ]
