# Generated by Django 3.0.4 on 2020-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='calendarId',
            field=models.CharField(default='전공 필수', max_length=30),
        ),
    ]
