# Generated by Django 3.0.4 on 2020-05-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='calendarID',
            new_name='calendarId',
        ),
    ]
