# Generated by Django 3.0.4 on 2020-05-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_lecture',
            name='codeClass',
            field=models.CharField(default='A', max_length=5),
        ),
    ]
