# Generated by Django 3.0.4 on 2020-06-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubcalendar',
            old_name='conutPer',
            new_name='countPer',
        ),
    ]
