# Generated by Django 3.0.4 on 2020-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0002_auto_20200506_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Professor_lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('lecture_type', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Professor_lecture',
            },
        ),
        migrations.CreateModel(
            name='Student_lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20)),
                ('professor', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('lecture_type', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Student_lecture',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('professor', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('lecture_type', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('lecture_type', models.CharField(max_length=30)),
                ('vote_status', models.CharField(max_length=30)),
                ('agree_votes', models.IntegerField()),
                ('reject_votes', models.IntegerField()),
                ('all_students', models.IntegerField()),
            ],
            options={
                'db_table': 'Vote',
            },
        ),
    ]
