# Generated by Django 3.0.4 on 2020-04-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0002_calendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
