# Generated by Django 3.0.4 on 2020-06-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0002_pubcalendar_pubcalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubcalendar',
            name='id',
        ),
        migrations.AlterField(
            model_name='pubcalendar',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
