# Generated by Django 3.0.4 on 2020-05-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0003_department_professor_lecture_student_lecture_subject_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor_lecture',
        ),
        migrations.AlterUniqueTogether(
            name='student_lecture',
            unique_together={('student_id', 'code')},
        ),
    ]
