# Generated by Django 3.0.4 on 2020-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0003_auto_20200825_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubcalendar',
            name='attendees',
            field=models.TextField(blank=True),
        ),
    ]
