# Generated by Django 3.0.4 on 2020-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0003_delete_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='isAllDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='state',
            field=models.CharField(default='Busy', max_length=30),
        ),
    ]
