# Generated by Django 3.0.4 on 2020-04-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0004_auto_20200424_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='isReadOnly',
            field=models.BooleanField(default=False),
        ),
    ]
