# Generated by Django 3.0.4 on 2020-11-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0004_pubcalendar_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ava_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCode', models.CharField(max_length=30)),
                ('status', models.FloatField()),
                ('avaTime', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Ava_Time',
            },
        ),
        migrations.CreateModel(
            name='Test_Vote',
            fields=[
                ('voteCode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('classCode', models.CharField(max_length=30)),
                ('lecType', models.CharField(max_length=30)),
                ('proName', models.CharField(max_length=30)),
                ('className', models.CharField(max_length=30)),
                ('voteStatus', models.CharField(max_length=30)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('choice1', models.IntegerField(default=0)),
                ('choice2', models.IntegerField(default=0)),
                ('choice3', models.IntegerField(default=0)),
                ('choice4', models.IntegerField(default=0)),
                ('choice1_Title', models.CharField(default=None, max_length=30)),
                ('choice2_Title', models.CharField(default=None, max_length=30)),
                ('choice3_Title', models.CharField(default=None, max_length=30)),
                ('choice4_Title', models.CharField(default=None, max_length=30)),
                ('totalCount', models.IntegerField()),
            ],
            options={
                'db_table': 'Test_Vote',
            },
        ),
    ]
