# Generated by Django 3.0.4 on 2020-05-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0004_auto_20200515_1355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_lecture',
            unique_together=set(),
        ),
    ]
