# Generated by Django 3.0.4 on 2020-11-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0005_ava_time_test_vote '),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_vote',
            name='choice1_Title',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AlterField(
            model_name='test_vote',
            name='choice2_Title',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AlterField(
            model_name='test_vote',
            name='choice3_Title',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AlterField(
            model_name='test_vote',
            name='choice4_Title',
            field=models.CharField(default='False', max_length=30),
        ),
    ]
