# Generated by Django 3.0.4 on 2020-04-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0005_calendar_isreadonly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='isReadOnly',
        ),
        migrations.AddField(
            model_name='calendar',
            name='calendarClass',
            field=models.CharField(default='public', max_length=30),
        ),
    ]
