# Generated by Django 3.0.4 on 2020-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0006_auto_20201106_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_Vote',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='code',
            new_name='classCode',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='lecture_type',
            new_name='className',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='name',
            new_name='lecType',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='professor_id',
            new_name='proName',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='agree_votes',
            new_name='totalCount',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='vote_status',
            new_name='voteStatus',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='all_students',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='reject_votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='choice1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice1_Title',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice2_Title',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice3_Title',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice4_Title',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AlterModelTable(
            name='vote',
            table='Test_Vote',
        ),
    ]
