# Generated by Django 3.0.4 on 2020-11-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0007_auto_20201106_1752'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vote',
            table='Vote',
        ),
    ]
