# Generated by Django 3.0.4 on 2020-04-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0007_calendar_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('studentID', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AlterField(
            model_name='calendar',
            name='calendar',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='calendarClass',
            field=models.CharField(default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='state',
            field=models.CharField(default='Busy', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='userID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='calendar',
            table='Calendar',
        ),
    ]
