# Generated by Django 3.0.4 on 2020-05-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0007_auto_20200518_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='calendarId',
            field=models.ForeignKey(default='전공 필수', on_delete=django.db.models.deletion.CASCADE, to='toast_cal.CalID'),
        ),
    ]
