# Generated by Django 3.0.4 on 2020-11-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0009_voteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='voteinfo',
            name='voteId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
