# Generated by Django 3.0.4 on 2020-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0010_auto_20200428_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='Student',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
