# Generated by Django 3.0.4 on 2020-11-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0010_auto_20201107_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voteinfo',
            old_name='stdudentID',
            new_name='studentID',
        ),
    ]
