# Generated by Django 3.0.4 on 2020-11-07 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_cal', '0011_auto_20201107_0416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteInfo',
        ),
    ]
